-- Run once in Supabase Dashboard > SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  timezone text not null default 'UTC',
  created_at timestamptz not null default now()
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day smallint not null check (day between 0 and 6),
  start_time time not null,
  end_time time not null,
  created_at timestamptz not null default now(),
  unique (user_id, day),
  check (start_time < end_time)
);

alter table public.profiles enable row level security;
alter table public.schedules enable row level security;

drop policy if exists "Profiles are publicly readable" on public.profiles;
create policy "Profiles are publicly readable"
  on public.profiles for select
  using (true);

drop policy if exists "Users update their own profile" on public.profiles;
create policy "Users update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Schedules are publicly readable" on public.schedules;
create policy "Schedules are publicly readable"
  on public.schedules for select
  using (true);

drop policy if exists "Users insert their own schedule" on public.schedules;
create policy "Users insert their own schedule"
  on public.schedules for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users update their own schedule" on public.schedules;
create policy "Users update their own schedule"
  on public.schedules for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users delete their own schedule" on public.schedules;
create policy "Users delete their own schedule"
  on public.schedules for delete
  using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username, timezone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'timezone', 'UTC')
  );

  insert into public.schedules (user_id, day, start_time, end_time)
  select new.id, day, '09:00'::time, '17:00'::time
  from generate_series(1, 5) as day;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
